/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthDevelopersRouteImport } from './routes/_auth/developers'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthBillingRouteImport } from './routes/_auth/billing'
import { Route as AuthSessionsIndexRouteImport } from './routes/_auth/sessions/index'
import { Route as AuthProjectsIndexRouteImport } from './routes/_auth/projects/index'
import { Route as AuthSessionsSessionIdRouteImport } from './routes/_auth/sessions/$sessionId'
import { Route as AuthProjectsProjectIdRouteImport } from './routes/_auth/projects/$projectId'
import { Route as AuthBillingSuccessRouteImport } from './routes/_auth/billing/success'
import { Route as AuthProjectsProjectIdSettingsRouteImport } from './routes/_auth/projects/$projectId_.settings'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDevelopersRoute = AuthDevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBillingRoute = AuthBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSessionsIndexRoute = AuthSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsIndexRoute = AuthProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSessionsSessionIdRoute = AuthSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsProjectIdRoute = AuthProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBillingSuccessRoute = AuthBillingSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => AuthBillingRoute,
} as any)
const AuthProjectsProjectIdSettingsRoute =
  AuthProjectsProjectIdSettingsRouteImport.update({
    id: '/projects/$projectId_/settings',
    path: '/projects/$projectId/settings',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/billing': typeof AuthBillingRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/developers': typeof AuthDevelopersRoute
  '/settings': typeof AuthSettingsRoute
  '/billing/success': typeof AuthBillingSuccessRoute
  '/projects/$projectId': typeof AuthProjectsProjectIdRoute
  '/sessions/$sessionId': typeof AuthSessionsSessionIdRoute
  '/projects/': typeof AuthProjectsIndexRoute
  '/sessions/': typeof AuthSessionsIndexRoute
  '/projects/$projectId/settings': typeof AuthProjectsProjectIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/billing': typeof AuthBillingRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/developers': typeof AuthDevelopersRoute
  '/settings': typeof AuthSettingsRoute
  '/billing/success': typeof AuthBillingSuccessRoute
  '/projects/$projectId': typeof AuthProjectsProjectIdRoute
  '/sessions/$sessionId': typeof AuthSessionsSessionIdRoute
  '/projects': typeof AuthProjectsIndexRoute
  '/sessions': typeof AuthSessionsIndexRoute
  '/projects/$projectId/settings': typeof AuthProjectsProjectIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/documentation': typeof DocumentationRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_auth/billing': typeof AuthBillingRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/developers': typeof AuthDevelopersRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/billing/success': typeof AuthBillingSuccessRoute
  '/_auth/projects/$projectId': typeof AuthProjectsProjectIdRoute
  '/_auth/sessions/$sessionId': typeof AuthSessionsSessionIdRoute
  '/_auth/projects/': typeof AuthProjectsIndexRoute
  '/_auth/sessions/': typeof AuthSessionsIndexRoute
  '/_auth/projects/$projectId_/settings': typeof AuthProjectsProjectIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documentation'
    | '/login'
    | '/privacy'
    | '/register'
    | '/sitemap.xml'
    | '/terms'
    | '/billing'
    | '/dashboard'
    | '/developers'
    | '/settings'
    | '/billing/success'
    | '/projects/$projectId'
    | '/sessions/$sessionId'
    | '/projects/'
    | '/sessions/'
    | '/projects/$projectId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documentation'
    | '/login'
    | '/privacy'
    | '/register'
    | '/sitemap.xml'
    | '/terms'
    | '/billing'
    | '/dashboard'
    | '/developers'
    | '/settings'
    | '/billing/success'
    | '/projects/$projectId'
    | '/sessions/$sessionId'
    | '/projects'
    | '/sessions'
    | '/projects/$projectId/settings'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/documentation'
    | '/login'
    | '/privacy'
    | '/register'
    | '/sitemap.xml'
    | '/terms'
    | '/_auth/billing'
    | '/_auth/dashboard'
    | '/_auth/developers'
    | '/_auth/settings'
    | '/_auth/billing/success'
    | '/_auth/projects/$projectId'
    | '/_auth/sessions/$sessionId'
    | '/_auth/projects/'
    | '/_auth/sessions/'
    | '/_auth/projects/$projectId_/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DocumentationRoute: typeof DocumentationRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/developers': {
      id: '/_auth/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof AuthDevelopersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/billing': {
      id: '/_auth/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthBillingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sessions/': {
      id: '/_auth/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AuthSessionsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/': {
      id: '/_auth/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthProjectsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sessions/$sessionId': {
      id: '/_auth/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AuthSessionsSessionIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/$projectId': {
      id: '/_auth/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthProjectsProjectIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/billing/success': {
      id: '/_auth/billing/success'
      path: '/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof AuthBillingSuccessRouteImport
      parentRoute: typeof AuthBillingRoute
    }
    '/_auth/projects/$projectId_/settings': {
      id: '/_auth/projects/$projectId_/settings'
      path: '/projects/$projectId/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof AuthProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthBillingRouteChildren {
  AuthBillingSuccessRoute: typeof AuthBillingSuccessRoute
}

const AuthBillingRouteChildren: AuthBillingRouteChildren = {
  AuthBillingSuccessRoute: AuthBillingSuccessRoute,
}

const AuthBillingRouteWithChildren = AuthBillingRoute._addFileChildren(
  AuthBillingRouteChildren,
)

interface AuthRouteChildren {
  AuthBillingRoute: typeof AuthBillingRouteWithChildren
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthDevelopersRoute: typeof AuthDevelopersRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthProjectsProjectIdRoute: typeof AuthProjectsProjectIdRoute
  AuthSessionsSessionIdRoute: typeof AuthSessionsSessionIdRoute
  AuthProjectsIndexRoute: typeof AuthProjectsIndexRoute
  AuthSessionsIndexRoute: typeof AuthSessionsIndexRoute
  AuthProjectsProjectIdSettingsRoute: typeof AuthProjectsProjectIdSettingsRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthBillingRoute: AuthBillingRouteWithChildren,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthDevelopersRoute: AuthDevelopersRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthProjectsProjectIdRoute: AuthProjectsProjectIdRoute,
  AuthSessionsSessionIdRoute: AuthSessionsSessionIdRoute,
  AuthProjectsIndexRoute: AuthProjectsIndexRoute,
  AuthSessionsIndexRoute: AuthSessionsIndexRoute,
  AuthProjectsProjectIdSettingsRoute: AuthProjectsProjectIdSettingsRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DocumentationRoute: DocumentationRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
